### ISSUE TITLE
How to make a round Trailing edge

### ISSUE THREAD

**Issue by OpenFoam-User** [pointwise/AirfoilGenerator#3]
Hello,
According to some CFD studies, a rounded trailing edge has some benefits. Is it possible to enhance this script to allow for using a rounded trailing edge?

Regards

**Comment by traviscarrigan** [comment]
Hello! Yes, absolutely. Please feel free to fork the script and add a rounded trailing edge option. We are happy to review any pull requests and merge them with the main branch.
